apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: production-
commonLabels:
  deploy-type: production

resources:
- app-deployment.yaml
- app-service.yaml
- nats-deployment.yaml
- nats-service.yaml
